// Default content for editable pages, used as fallback if no override is saved.
export const PAGE_DEFAULTS = {
  home: {
    hero_title_line1: "KENYA,",
    hero_title_line2: "CURATED PERSONALLY.",
    hero_subtitle: "Private safaris, wild landscapes and meaningful encounters — thoughtfully designed around you.",
    hero_cta_primary: "Plan Your Journey",
    hero_cta_secondary: "Explore Adventures",
    hero_proof_text: "Private Kenya journeys shaped with care, context and local knowledge.",
    hero_image_url: "",
    hero_image_as_background: true,
    hero_hide_search: true,
    hero_focal_x: 50, // 0 = left, 100 = right
    hero_focal_y: 50, // 0 = top,  100 = bottom
    hero_bg_size: "cover" as "cover" | "contain",
  },
  about: {
    eyebrow: "The feeling of Kenya",
    title_line1: "KENYA ISN'T JUST",
    title_line2: "A DESTINATION.",
    title_line3: "IT'S A FEELING.",
    body: "The Baobab Collective designs private journeys through Kenya with the calm confidence of people who know the place intimately — its landscapes, its lodges, its guides, and the small moments that make a journey stay with you.",
    image_left_url: "",
    image_right_url: "",
  },
  about_mission: {
    eyebrow: "Our Mission",
    title: "Journeys with purpose",
    body: "Every safari we design supports conservation, community, and the guides who make Africa feel like home. We believe travel should give back as much as it gives.",
  },
  about_values: {
    eyebrow: "What guides us",
    title: "Our values",
    value_1_title: "Conservation-led",
    value_1_body: "Each journey supports the wild places we love.",
    value_2_title: "Community-first",
    value_2_body: "We partner with local guides and lodges.",
    value_3_title: "Slow travel",
    value_3_body: "Fewer destinations. Deeper connections.",
    value_4_title: "Bespoke by design",
    value_4_body: "No two itineraries are ever the same.",
  },
  about_team: {
    eyebrow: "The people",
    title: "Meet the collective",
    body: "A small team of Africa specialists, guides and storytellers with deep roots in Kenya.",
    image_1_url: "",
    image_1_name: "Michael D'Souza",
    image_1_role: "Co-Founder",
    image_1_bio:
      "Kenya has been home for most of my life. I created Baobab to share the places and people I know best.",
    image_2_url: "",
    image_2_name: "Samra D'Souza",
    image_2_role: "Co-Founder",
    image_2_bio:
      "Samra brings a deeply personal eye to each journey, shaping travel with warmth, care and an instinct for meaningful connection.",
    image_3_url: "",
    image_3_name: "",
    image_3_role: "",
    image_3_bio: "",
    image_4_url: "",
    image_4_name: "",
    image_4_role: "",
    image_4_bio: "",
  },

  private_travel: {
    eyebrow: "Private Travel",
    title: "Designed entirely around you.",
    subtitle: "For travellers who want something truly bespoke — every camp, guide and moment shaped to your story.",
    success_title: "Request received",
    success_body:
      "A confirmation has been sent to your inbox. One of our journey designers will reach out within 48 hours.",
    submit_label: "Request my bespoke journey",
  },
  home_trust: {
    item_1_title: "Kenya Specialists",
    item_1_subtitle: "Born from a deep, lifelong connection",
    item_2_title: "Tailor-Made Journeys",
    item_2_subtitle: "Designed around you — no catalog packages",
    item_3_title: "Personally Curated",
    item_3_subtitle: "Every camp, lodge & guide walked & vetted",
    item_4_title: "24/7 On-Ground Support",
    item_4_subtitle: "Seamless care from landing to departure",
  },
  home_find_journey: {
    eyebrow: "Find Your Journey",
    title: "What kind of journey are you dreaming of?",
    body: "Whether you are drawn to the pulse of the Great Migration, secluded romantic sanctuaries, or coastal dhow sailing, we curate every detail around your vision.",
    card_1_image: "",
    card_2_image: "",
    card_3_image: "",
    card_4_image: "",
    card_5_image: "",
    card_6_image: "",
  },
  home_adventures: {
    eyebrow: "Signature Adventures",
    title: "Find Your Adventure",
    body: "Journeys designed around the places, experiences and moments that make Kenya unforgettable.",
    cta_label: "Explore All Journeys",
  },
  home_destinations: {
    eyebrow: "The Continent",
    title: "DESTINATIONS",
    body: "From the deltas of Botswana to the highlands of Ethiopia — explore where each journey could take you.",
    cta_label: "Explore destinations",
    hidden: false,
  },
  home_why_baobab: {
    eyebrow: "Quiet Expertise",
    title: "Why The Baobab Collective?",
    body: "We operate as your personal Kenya travel designer and advisor — bringing deep local context, unhurried pacing, and genuine care to every moment of your adventure.",
    pillar_1_num: "01",
    pillar_1_title: "Kenya is Home",
    pillar_1_body: "We're not simply selling Kenya from a desk abroad. We know its rhythms, seasons, guides, and secret corners personally.",
    pillar_2_num: "02",
    pillar_2_title: "Personally Curated",
    pillar_2_body: "Every journey is designed from scratch around you, your travelling party and your pace — never selected from a rigid catalogue.",
    pillar_3_num: "03",
    pillar_3_title: "Trusted Local Relationships",
    pillar_3_body: "Decades of friendship with conservationists, master trackers and private camp owners unlock encounters ordinary tourists never see.",
    pillar_4_num: "04",
    pillar_4_title: "Travel With Purpose",
    pillar_4_body: "Your journey directly contributes to wildlife conservation, anti-poaching, and empowering local community custodians.",
  },
  home_founders: {
    eyebrow: "Direct Personal Connection",
    title: "Meet Your Journey Designers",
    body: "When you plan with The Baobab Collective, you do not speak to a call center or browse a mass catalog. You design your safari directly with people who have lived the land, walked every camp, and built decades of trusted relationships in Kenya.",
    cta_label: "Meet the Collective",
    founder_1_name: "Michael D'Souza",
    founder_1_role: "Co-Founder & Expedition Lead",
    founder_1_tag: "Lifelong Kenya Resident",
    founder_1_quote: "Kenya has been home for most of my life. I created Baobab to share the wild, intimate places and the people I know and respect most.",
    founder_1_image: "",
    founder_2_name: "Samra D'Souza",
    founder_2_role: "Co-Founder & Experience Curator",
    founder_2_tag: "Journey Architect",
    founder_2_quote: "We believe luxury is not about excess, but about intimacy, soul, and time well-spent in places that truly leave a lasting mark.",
    founder_2_image: "",
  },
  home_lodges: {
    eyebrow: "Places we love",
    title: "PARTNER LODGES",
    body: "Every camp and lodge has been walked, slept in, and chosen for soul as much as setting.",
    cta_label: "Discover lodges",
  },
  home_impact: {
    eyebrow: "Responsible Tourism",
    title: "Your Journey's Impact",
    body: "We believe travel in Kenya should give back as much as it gives. When designed with intention, a safari is one of the most powerful catalysts for conservation and community resilience on earth.",
    pillar_1_subtitle: "Securing wilderness corridors",
    pillar_1_title: "Wild Habitat & Conservation",
    pillar_1_body: "Every safari directly funds conservancy lease fees, ranger patrols, and wildlife protection in critical biodiversity areas across Kenya.",
    pillar_2_subtitle: "Equitable local benefit",
    pillar_2_title: "Community Partnerships",
    pillar_2_body: "We prioritize locally-owned camps, indigenous guides, and community projects ensuring travel revenue stays directly in the hands of traditional custodians.",
    pillar_3_subtitle: "Slow, respectful exploration",
    pillar_3_title: "Ethical, Low-Impact Footprint",
    pillar_3_body: "Small private parties, solar-powered eco-camps, and strict non-invasive wildlife protocols ensure Africa remains wild for generations to come.",
  },
  home_how_it_works: {
    eyebrow: "Seamless Planning",
    title: "Your Journey Starts Here",
    body: "Planning a private safari with The Baobab Collective is calm, collaborative, and entirely stress-free.",
    cta_label: "Start Planning My Journey",
    step_1_num: "01",
    step_1_title: "Tell Us What You're Dreaming Of",
    step_1_body: "A quick conversation about your dates, travelling party, travel style, and the sights and wildlife you long to see.",
    step_2_num: "02",
    step_2_title: "We Design Your Journey",
    step_2_body: "We create a thoughtful, completely personalised itinerary based on our firsthand knowledge and local relationships.",
    step_3_num: "03",
    step_3_title: "Refine The Details",
    step_3_body: "Together, we talk through camps, pacing, private guides, unique encounters, and make adjustments until it feels perfect.",
    step_4_num: "04",
    step_4_title: "Experience Kenya",
    step_4_body: "From the moment you step off the plane in Nairobi, our on-ground team takes care of every single detail.",
  },
  home_final_cta: {
    eyebrow: "Begin Your Journey",
    title_line1: "Your Kenya is waiting.",
    title_line2: "Let's create it together.",
    body: "Tell us about your ideal travel dates and dreams. We'll respond within 24 hours with an initial private itinerary sketch.",
    cta_label: "Plan Your Journey",
  },
  home_journal: {
    eyebrow: "Stories from the road",
    title_line1: "A JOURNAL",
    title_line2: "OF PLACES,",
    title_line3: "PEOPLE & LIGHT.",
    body: "Field notes, travel ideas and considered guidance for journeys that begin before you board the plane.",
    cta_label: "Explore the Journal",
  },
  home_instagram: {
    heading: "Follow Our Journeys",
    handle: "@thebaobabcollective",
    url: "https://instagram.com/thebaobabcollective",
    image_1_url: "",
    image_1_caption: "",
    image_2_url: "",
    image_2_caption: "",
    image_3_url: "",
    image_3_caption: "",
    image_4_url: "",
    image_4_caption: "",
    image_5_url: "",
    image_5_caption: "",
    image_6_url: "",
    image_6_caption: "",
    image_7_url: "",
    image_7_caption: "",
  },

  top_bar: {
    text: "Curated Safari Journeys. Authentic Connections. Extraordinary Experiences.",
    enabled: true,
  },
  contact: {
    eyebrow: "We'd love to hear from you",
    title_line1: "Let's Plan",
    title_line2: "Your Journey",
    body: "Tell us a little about who's travelling, when, and the kind of experience you're after. One of our journey designers will respond within 24 hours with first ideas and next steps.",
    form_title: "Share Your Vision",
    form_intro:
      "Open our detailed enquiry form — tell us who's travelling, when, your budget, and the experiences you're dreaming of. We'll respond within 24 hours.",
    form_cta: "Open Enquiry Form",
    email_label: "Email us",
    phone_label: "Call / WhatsApp",
    instagram_label: "Instagram",
    facebook_label: "Facebook",
    instagram_url: "https://instagram.com/thebaobabcollective",
    instagram_handle: "@thebaobabcollective",
    facebook_url: "https://facebook.com/thebaobabcollective",
    facebook_handle: "/thebaobabcollective",
  },
  lodges_index: {
    eyebrow: "Where you'll stay",
    title: "Partner Lodges",
    subtitle: "Every camp and lodge we work with has been walked, slept in, and chosen for soul as much as setting.",
  },
  adventures_index: {
    eyebrow: "Signature Adventures",
    title: "Wild Africa, Deeply Lived",
    subtitle: "Walking safaris, mokoro expeditions, desert traverses, gorilla treks and migration chases.",
    // Rhythm section (editable)
    rhythm_eyebrow: "A Day in the Field",
    rhythm_title: "The rhythm of an adventure day.",
    rhythm_body:
      "No two days repeat — but the cadence is the same. Up before the bush, slow through the heat, alive again at dusk.",
    // Signature section header
    signature_eyebrow: "Signature Adventures",
    signature_title: "Journeys we'd take ourselves.",
    signature_body: "Each is a starting point — every detail is reshaped around you, your dates and your pace.",
    // Show/hide sections
    show_rhythm: true,
    show_enquiry_cta: true,
  },
  testimonials_page: {
    eyebrow: "Guest Stories",
    title: "In their words",
    subtitle: "The clearest measure of a journey is how it stays with you afterwards.",
    show_metrics: true,
    metric_1_value: "12+",
    metric_1_label: "Years of journeys",
    metric_2_value: "800+",
    metric_2_label: "Travellers hosted",
    metric_3_value: "40+",
    metric_3_label: "Lodge partners",
    cta_title: "Let your story begin here",
    cta_button: "Start planning",
  },
  // Detail-page templates (shared intros / CTAs)
  detail_journey: {
    enquire_cta: "Enquire about this journey",
    intro_eyebrow: "The Journey",
    related_title: "Other journeys you might love",
  },
  detail_lodge: {
    enquire_cta: "Enquire about this lodge",
    intro_eyebrow: "The Lodge",
    related_title: "Similar lodges",
  },
  // Footer copy (columns are managed via Menu editor; socials are editable here)
  footer: {
    newsletter_title: "Newsletter",
    newsletter_body: "Receive travel inspiration and special offers.",
    newsletter_placeholder: "Your email address",
    copyright: "© The Baobab Collective {year} | All Rights Reserved",
    contact_heading: "Get in Touch",
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    linkedin_url: "",
    twitter_url: "",
    youtube_url: "",
  },
  // 404 / Auth / global SEO
  not_found: {
    title: "Page not found",
    body: "The page you're looking for doesn't exist or has been moved.",
    cta_label: "Go home",
  },
  auth_page: {
    title: "Admin sign in",
    subtitle: "Access The Baobab Collective admin.",
    email_label: "Email",
    password_label: "Password",
    submit_label: "Sign in",
  },
  seo: {
    site_name: "The Baobab Collective",
    default_title: "The Baobab Collective — Curated Safari Journeys",
    default_description:
      "Luxury curated safari experiences in Africa. Authentic connections, conservation-led journeys, and extraordinary moments.",
    default_og_image: "",
  },
} as const;

export type PageDefaults = typeof PAGE_DEFAULTS;
export type PageKey = keyof PageDefaults;

export function mergePageContent<K extends PageKey>(
  key: K,
  override: Record<string, unknown> | null | undefined,
): PageDefaults[K] {
  return { ...PAGE_DEFAULTS[key], ...(override ?? {}) } as PageDefaults[K];
}
